Repository discordjs/discord-toolkit-bot, pull requests merged in 2022-10, with the labels that each got.

#1 feat: handling and initial commands
  .env.example
  .eslintrc.json
  .gitattributes
  .gitignore
  .prettierrc.json
  .swcrc
  LICENSE
  lintstagedrc.json
  package.json
  src/Command.ts
  src/Component.ts
  src/Event.ts
  src/commands/bitfields.ts
  src/commands/snowflakeInfo.ts
  src/commands/sub/bitfields/intents.ts
  src/commands/sub/bitfields/permissions.ts
  src/commands/userinfo.ts
  src/components/.gitkeep
  src/deploy.ts
  src/events/interactionCreate.ts
  src/events/ready.ts
  src/events/threadCreate.ts
  src/index.ts
  src/interactions/ArgumentsOf.ts
  src/interactions/InteractionOptions.ts
  src/interactions/context/intentsLookupContext.ts
  src/interactions/context/userinfoContext.ts
  src/interactions/index.ts
  src/interactions/slash/bitfieldLookup.ts
  src/interactions/slash/snowflakeInfo.ts
  src/interactions/slash/userinfo.ts
  src/tokens.ts
  src/util/buttons.ts
  src/util/commands.ts
  src/util/components.ts
  src/util/constants.ts
  src/util/dynamicImport.ts
  src/util/formatting.ts
  src/util/index.ts
  src/util/logger.ts
  src/util/messageActionRow.ts
  src/util/webhooks.ts
  tsconfig.eslint.json
  tsconfig.json
  yarn.lock
Labels: semver:minor

#2 chore(ci): build workflow
  .github/workflows/tests.yml
Labels: ci

#3 chore(ci): ignore dist with prettier validation
  .prettierignore
Labels: ci

#4 refactor(handler): use yuudachi framework
  package.json
  src/Command.ts
  src/Component.ts
  src/Event.ts
  src/commands/bitfields.ts
  src/commands/snowflakeInfo.ts
  src/commands/sub/bitfields/intents.ts
  src/commands/sub/bitfields/permissions.ts
  src/commands/userinfo.ts
  src/components/.gitkeep
  src/deploy.ts
  src/events/interactionCreate.ts
  src/events/ready.ts
  src/events/threadCreate.ts
  src/index.ts
  src/interactions/ArgumentsOf.ts
  src/interactions/InteractionOptions.ts
  src/tokens.ts
  src/util/buttons.ts
  src/util/commands.ts
  src/util/components.ts
  src/util/dynamicImport.ts
  src/util/logger.ts
  src/util/messageActionRow.ts
  src/util/webhooks.ts
  yarn.lock
Labels: refactor

#5 feat(GitHub Lines): parse and send the content of github urls
  src/events/github/messageCreate.ts
  src/functions/github/handler.ts
  src/functions/github/regex.ts
  src/functions/github/utils.ts
  src/index.ts
  src/util/array.ts
  src/util/constants.ts
Labels: semver:minor
